### ISSUE TITLE
ERROR: triton-2.1.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.

### ISSUE THREAD

**Issue by MetaMind09** [MackinationsAi/Upgraded-Depth-Anything-V2#5]
I get this error when trying installing via one_click_install.
(ERROR: triton-2.1.0-cp310-cp310-win_amd64.whl is not a supported wheel on this platform.)

Was trying downloading it manually and put it in destination dir but still same issue.

Tried: venv\scripts\activate & hit enter, then paste in pip install triton-2.1.0-cp310-cp310-win_amd64.whl —no-cache-dir
but then I get:
"Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -n"

**Comment by MackinationsAi** [comment]
```
venv\scripts\activate
pip install triton-2.1.0-cp310-cp310-win_amd64.whl --no-cache-dir
```
(reddit fuses together -- into — which is why you got that particular error trying to install manually, my apologies). Let me know if that fix works, & triton is not essential for udav2 to work, just provides a bit of acceleration.

**Comment by MetaMind09** [comment]
Thanks but I still get the same error.

Anyway if triton (and  xformers) is not necessary how do I use run_video-depth?
When I enter: run_video-depth   into cmd I get:

"Traceback (most recent call last):
  File "E:\depthany\Upgraded-Depth-Anything-V2\run_video-depth.py", line 7, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'"

**Comment by MackinationsAi** [comment]
To me it sounds like nothing has installed installed... You need to have python 3.10.11 or above installed, cuda 11.8 or above installed & you need to make sure that both are installed w/ the right environment variable path structures? 

OR if you are just doing python run_video-depth.py & not using the run_video-depth.bat it sounds like perhaps you may be trying to run it w/o activating the venv\scripts\activate before hand perhaps?

My suggestion is delete the repo, re ```git clone https://github.com/MackinationsAi/Upgraded-Depth-Anything-V2.git``` then once it's been cloned to where you want it to be staying in that same cmd terminal & ```cd Upgraded-Depth-Anything-V2``` then finally ```one_click_install.bat```

Now everything should install properly (fingers-crossed), if you are using the .py CLI scripts instead of the .bat connected to each CLI .py script in cmd you have to activate the ```venv\scripts\activate``` each time before running ```run_video-depth.py``` which is why I highly recommend using the .bat scripts for CLI. Hopefully that breakdown isn't to complicated, I real want to help you get this up & running!

**Comment by MetaMind09** [comment]
Again thank you Macki for this longwinded response.

I (re)installed pytorch manually using anaconda coz of the error I got: "ModuleNotFoundError: No module named 'torch'" " 
I still werent able to install triton but run_video-depth.bat is working fine now which was my intention using this program.
btw DepthAny2 does not have the function to actually output a full SBS or AboveBottom 3D format right? 
I only see depthmap videos generating.
Using run_image-depth_16bit.bat gives me "out of video memory - 28GB" error but run_image-depth_8bit works fine.

I ve RTX 2080 so Cuda 11.8 should work right?

Anyway big thumps up for all your help and especially putting this alltogether and sharing it to the community.
Its highly appreciated!

**Comment by MetaMind09** [comment]
I ve Python 3.12.4 btw

**Comment by MackinationsAi** [comment]
Glad you were able to get it somewhat working. I'm running on python 3.10.11, cuda 11.8 & a RTX 4090. So that is what this build was tested on. Based on the your set up I don't think 8gbs of VRAM is enough when it comes to creating 16bit images. (I will look into optimizations for the 16bit functionality for lower gpu VRAM strengths). As for your other question no DepthAny2 doesn't have a function to produce outputs in  a full SBS or AboveBottom 3D format. Though that type of functionality is on my radar for future updates!

**Comment by MetaMind09** [comment]
I think your project is more catered to 2D/3D artists etc. 
I wasnt aware of that, I m sorry.
After researching a bit there already is a repo specifically optimized for video generation named: iw3
Anyway thanks for your hard work and kind responses.
