### ISSUE TITLE
Error I can't solve

### ISSUE THREAD

**Issue by BlinkerHigh** [MackinationsAi/Upgraded-Depth-Anything-V2#7]
Hello, I got this error when using Depth Anything v2, any idea what's causing it?

FETCH DATA from: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI-Manager\extension-node-map.json [DONE]
# ðŸ˜ºdzNodes: LayerStyle -> [1;33mWarning: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size. [m
# ðŸ˜ºdzNodes: LayerStyle -> [1;33mWarning: D:\ComfyUI\ComfyUI\custom_nodes\ComfyUI_LayerStyle\custom_size.ini not found, use default size. [m
got prompt
model_path is D:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\LiheYoung/Depth-Anything\checkpoints\depth_anything_vitl14.pth
using MLP layer as FFN
model_path is D:\ComfyUI\ComfyUI\custom_nodes\comfyui_controlnet_aux\ckpts\depth-anything/Depth-Anything-V2-Large\depth_anything_v2_vitl.pth
using MLP layer as FFN
Prompt executed in 16.07 seconds

**Comment by MackinationsAi** [comment]
This is a stand-alone repo for Upgraded Depth Anything V2 (not a ComfyUI custom_node). If you're having issues w/ comfyui_controlnet_aux submit an issues ticket [here](https://github.com/Fannovel16/comfyui_controlnet_aux/issues), or wherever the repo/extension/node your issues is actually connected to in future. 

However, that being said, in this cause I do know what your issue is. Both depth_anything_vitl14.pth & depth_anything_v2_vitl.pth are **not** controlnet models, they're depth-estimation models, & thus will now work w/ controlnet based on how you've got your workflow set up currently. 

Install this custom_node - [ComfyUI-DepthAnythingV2](https://github.com/kijai/ComfyUI-DepthAnythingV2) (also found in ComfyUI-Manager), & pass the preprocessed Depth_Anything_V2 *greyscale* depth map output image to controlnet & you'll be good to go. Hope that helps 👍🏼

**Comment by BlinkerHigh** [comment]
Thanks mate, appreciate it.
